from XL.ReadAndGetStatic import *
from XL.configuration import *


#Print All Paramaters on Simcard

#MF Layer 1

print ("---MF---")
find(Level1PINs,'Level1PINs')
Result_Level2PINs = find(Level2PINs,'Level2PINs')
Result_Level2PINs = find(Level5PINs,'Level5PINs')
Result_Level6PINs = find(Level6PINs,'Level6PINs')
Result_DIR = find(DIR,'DIR')

Result_ICCID = find(ICCID,'ICCID')
Result_read_iccid = read_iccid()

Result_PL = find(PL,'PL')
Result_ARR1 = find(ARR1,'ARR')


#DF_GSM
print("")
print ("---DF GSM---")
open(DF_GSM)

Result_KeyMan = find(KeyMan,'KeyMan')
Result_Ki = find(Ki,'Ki')
Result_OPcKey = find(OPcKey,'OPcKey')
Result_AUTHCNT = find(AUTHCNT,'AUTHCNT')
Result_LP = find(LP,'LP')

Result_IMSI = find(IMSI,'IMSI')
Result_read_imsi = read_imsi()

Result_Kc1 = find(Kc1,'Kc')
Result_PLMNsel = find(PLMNsel,'PLMNsel')
Result_HPLMN = find(HPLMN,'HPLMN')
Result_ACMmax = find(ACMmax,'ACMmax')
Result_SST = find(SST,'SST')
Result_ACM = find(ACM,'ACM')
Result_GID1 = find(GID1,'GID1')
Result_GID2 = find(GID2,'GID2')
Result_PUCT = find(PUCT,'PUCT')
Result_CBMI = find(CBMI,'CBMI')
Result_SPN = find(SPN,'SPN')
Result_CBMID = find(CBMID,'CBMID')
Result_BCCH = find(BCCH,'BCCH')
Result_ACC = find(ACC,'ACC')
Result_FPLMN = find(FPLMN,'FPLMN')
Result_LOCI = find(LOCI,'LOCI')
Result_AD = find(AD,'AD')
Result_PHASE = find(PHASE,'PHASE')
Result_VGCS = find(VGCS,'VGCS')
Result_VGCSS = find(VGCSS,'VGCSS')
Result_VBS = find(VBS,'VBS')
Result_VBSS = find(VBSS,'VBSS')
Result_eMLPP = find(eMLPP,'eMLPP')
Result_AAeM = find(AAeM,'AAeM')
Result_ECC = find(ECC,'ECC')
Result_CBMIR = find(CBMIR,'CBMIR')
Result_NIA1 = find(NIA1,'NIA')
Result_KcGPRS1 = find(KcGPRS1,'KcGPRS')
Result_LOCIGPRS = find(LOCIGPRS,'LOCIGPRS')
Result_PLMNwACT = find(PLMNwACT,'PLMNwACT')
Result_OPLMNwACT = find(OPLMNwACT,'OPLMNwACT')
Result_HPLMNACT = find(HPLMNACT,'HPLMNACT')
Result_CPBCCH1 = find(CPBCCH1,'CPBCCH')
Result_INVSCAN1 = find(INVSCAN1,'INVSCAN')
Result_RFMRPH = find(RFMRPH,'RFMRPH')
Result_RFMPRO_SMS_NOK = find(RFMPRO_SMS_NOK,'RFMPRO_SMS_NOK')
Result_EF_RFMPRO_SMS = find(EF_RFMPRO_SMS,'EF_RFMPRO_SMS')
Result_RFMPRO_NOK = find(RFMPRO_NOK,'RFMPRO_NOK')
Result_RFMPRO = find(RFMPRO,'RFMPRO')
Result_RFMCNTR = find(RFMCNTR,'RFMCNTR')
Result_RFMData = find(RFMData,'RFMData')
Result_CSMS = find(CSMS,'CSMS')
Result_OTACLRAC = find(OTACLRAC,'OTACLRAC')
Result_OTARFMAC = find(OTARFMAC,'OTARFMAC')




#DF_Telecom
print("")
print ("---DF Telecom---")
open(DF_TELECOM)

#Result_Find_MSISDN = find(MSISDN,'MSISDN')
#Result_Read_msisdn = read_msisdn()
#Result_ARR2 = find(ARR2,'ARR')

Result_ADN = find_adn(ADN,'ADN')
#Result_Read_ADN = read_adn()
#print ('ADN : ', Result_Read_ADN)

Result_FDN = find(FDN,'FDN')
Result_SMS = find(SMS,'SMS')
Result_CCP = find(CCP,'CCP')
Result_MSISDN = find(MSISDN,'MSISDN')
Result_SMSP = find(SMSP,'SMSP')
Result_SMSS = find(SMSS,'SMSS')
Result_LND = find(LND,'LND')
Result_SMSR = find(SMSR,'SMSR')
Result_SDN = find(SDN,'SDN')
Result_EXT1 = find(EXT1,'EXT1')
Result_EXT2 = find(EXT2,'EXT2')
Result_EXT3 = find(EXT3,'EXT3')
Result_BDN = find(BDN,'BDN')
Result_EXT4_1 = find(EXT4_1,'EXT4')
Result_SUME = find(SUME,'SUME')



#ADF USIM
print("")
print ("---ADF USIM---")
open(ADF_USIM)
print ("---Missing Part----")
#find(OPcKey,'OPcKey')
find(SQNMax,'SQNMax')
find(SEQtable,'SEQtable')
find(D,'D')
find(L,'L')
find(MilenageConst,'MilenageConst')
find(Keys,'Keys')
find(KeysPS,'KeysPS')
find(DCK,'DCK')
#find(Level2PINs,'Level2PINs')
Result_K =  find(K,'K')
Result_LI = find(LI,'LI')
Result_ARR3 = find(ARR3,'ARR')
Result_HPPLMN = find(HPPLMN,'HPPLMN')
find(CNL,'CNL')
Result_UST =  find(UST,'UST')
find(Ext5,'Ext5')
find(CCP2,'CCP2')
find(Ext4_2,'Ext4')
find(EST,'EST')
find(ACL,'ACL')
find(CMI,'CMI')
find(TRESHOLD,'TRESHOLD')
Result_HPLMNwAcT = find(HPLMNwAcT,'HPLMNwAcT')
find(PSLOCI,'PSLOCI')
find(ICI,'ICI')
find(OCI,'OCI')
find(ICT,'ICT')
find(OCT,'OCT')
find(HiddenKey,'HiddenKey')
find(NETPAR,'NETPAR')
Result_PNN =  find(PNN,'PNN')
Result_OPL =  find(OPL,'OPL')
find(MBDN,'MBDN')
find(Ext6,'Ext6')
find(MBI,'MBI')
find(MWIS,'MWIS')
find(CFIS,'CFIS')
find(Ext7,'Ext7')
Result_SPDI =  find(SPDI,'SPDI')
find(MMSN,'MMSN')
find(Ext8,'Ext8')
find(MMSICP,'MMSICP')
find(MMSUP,'MMSUP')
find(MMSUCP,'MMSUCP')
find(NIA2,'NIA')
find(VGCSCA,'VGCSCA')
find(VBSCA,'VBSCA')
find(GBABP,'GBABP')
find(MSK,'MSK')
find(MUK,'MUK')
find(EHPLMN,'EHPLMN')


#DF_PhoneBook
print("")
print ('---DF_PhoneBook---')
open(DF_PhoneBook)
find(PBR,'PBR')
find(PSC,'PSC')
find(CCP2,'CC')
find(PUID,'PUID')

print("")
print ('Other')
print ('MSISDN : ', Result_Read_msisdn[0],Result_Read_msisdn[1],Result_Read_msisdn[2])
print ('IMSI   : ', Result_read_imsi)
print ('ICCID  : ', Result_read_iccid)



